### ISSUE TITLE
Example ex-push.py does not works

### ISSUE THREAD

**Issue by julienfr112** [wrobell/aionn#2]
> File "/usr/local/lib/python3.5/dist-packages/aionn/socket.py", line 122, in _notify_send
>     data = ffi.from_buffer(self._data)
> TypeError: from_buffer() cannot return the address of the raw string within a bytes or unicode or bytearray object

ubuntu 16.04, Python 3.5.2, aionn installed with pip3

pip3 freeze | grep nnpy
nnpy==1.3

**Comment by wrobell** [comment]
What version of cffi are you using?

**Comment by julienfr112** [comment]
my mistake, ubuntu 16.04 has an old version of nanomsg. work with nanomsg 1.0.
i updated ccfi also ...

**Comment by wrobell** [comment]
IMHO, this looked like you were using earlier version of cffi. Just in case I have changed setup.py file to require latest version of cffi, see https://github.com/wrobell/aionn/commit/14f7d6f1e1d5c0526f242b47631deefd821d1a80.

Thanks for the report.
